
server:
  port: 9528

spring:
  application:
    name: cloudalibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      # 是否开启网关
      enabled: true
      routes:
      - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001          #匹配后提供服务的路由地址
        uri: lb://nacos-payment-provider #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/nacos/**         # 断言，路径相匹配的进行路由
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719    #指定应用于Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
      filter:
        enabled: false
#      datasource:
#        ds1:
#          nacos:
#            server-addr: localhost:8848
#            dataId: cloudalibaba-gateway
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

